[package]
name = "metriken"
version = "0.2.0"
edition = "2021"
authors = [
	"Brian Martin <brian@iop.systems>",
	"Sean Lynch <sean@iop.systems>",
]
license = "MIT OR Apache-2.0"
description = "A fast and lightweight metrics library"
homepage = "https://github.com/pelikan-io/rustcommon"
repository = "https://github.com/pelikan-io/rustcommon"

[dependencies]
histogram = { version = "0.7.3", path = "../histogram" }
heatmap = { version = "0.7.5", path = "../heatmap" }
linkme = "0.3.3"
parking_lot = "0.12.1"
metriken-derive = { version = "0.2.0", path = "./derive" }
phf = { version = "0.11.2", features = ["macros"] }